@component('mail::message')

Hello {{ $minusername }} welcome to Osiris HRIS-Payroll Web application.

Admin {{ $adminname }} added you

Here's your account credentials

Employee ID: {{ $employee_id }}

Email: {{ $miniuseremail }}

Default Password: Your employee id - follow right capitalization plus '@' symbol plus word 'osiris' 

sample: EID0000100@osiris

Note: default password was auto generated by our system, kindly visit our web application address right away to change your password 

immediately for security reasons.

Just simply login using your registered email and default password or select forgot password option then used your registered email address

If you login for the first time, our web app will prompt a email verification process.

Once again welcome to Osiris and goodluck to your journey.

@component('mail::button',['url' => $url])
    Visit Website
@endcomponent
    
@endcomponent